<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-KR2Q4MNQ" ignored="0" name="RetryMulitpleFailedTestCases" tests="3" failures="2" timestamp="13 Feb 2018 00:57:18 GMT" time="0.063" errors="0">
  <testcase name="Test1" time="0.016" classname="testngdemo.RetryFailedTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at testngdemo.RetryFailedTests.Test1(RetryFailedTests.java:10)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.0" classname="testngdemo.RetryFailedTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]at testngdemo.RetryFailedTests.Test2(RetryFailedTests.java:16)... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.0" classname="testngdemo.RetryFailedTests"/>
</testsuite> <!-- RetryMulitpleFailedTestCases -->
